package com.github.se.studybuddies.navigation

object Route {
  const val START = "Start"
  const val LOGIN = "LoginScreen"
  const val GROUPSHOME = "GroupsHome"
  const val CREATEGROUP = "CreateGroup"
  const val DELETEGROUP = "DeleteGroup"
  const val GROUPSETTING = "GroupSetting"
  const val LEAVEGROUP = "LeaveGroup"
  const val GROUP = "Group"
  const val CALENDAR = "Calendar"
  const val SETTINGS = "Settings"
  const val ACCOUNT = "AccountSettings"
  const val CREATEACCOUNT = "CreateAccount"
  const val SOLOSTUDYHOME = "SoloStudyHome"
  const val FLASHCARD = "FlashCard"
  const val TODOLIST = "Todo list"
  const val FOCUSMODE = "Focus Mode"
  const val TIMER = "Timer"
  const val DAILYPLANNER = " Daily Planner"

  const val SHAREDTIMER = "Shared timer"

  const val CREATETODO = "CreateToDo"
  const val EDITTODO = "EditToDo"
  const val TOPIC = "Topic"
  const val TOPICRESOURCES = "Topic resources"
  const val TOPIC_SETTINGS = "Topic settings"
  const val CHAT = "Chat"
  const val TOPICCREATION = " TopicCreaction"
  const val DIRECT_MESSAGE = "DirectMessage"
  const val VIDEOCALL = "VideoCall"
  const val CALLLOBBY = "CallLobby"
  const val MAP = "Map"
  const val PLACEHOLDER = "Placeholder"
}
